
  CREATE TABLE "SYSTEM"."OC_TBL_CANDIDATES" 
   (	"CANDIDATE_ID" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"URL_IS_ACTIVE" CHAR(1 BYTE), 
	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"INTERVIEWER_ID" VARCHAR2(10 BYTE), 
	"CANDIDATE_FULL_NAME" VARCHAR2(50 BYTE), 
	"URL_CREATED_TIME" TIMESTAMP (6), 
	"URL_EXPIRY_TIME" TIMESTAMP (6), 
	"TECHNOLOGY" VARCHAR2(10 BYTE), 
	"YEAR_OF_EXPERIENCE" FLOAT(126), 
	"ASSESSMENT_IS_STARTED" CHAR(1 BYTE), 
	"ASSESSMENT_START_TIME" TIMESTAMP (6), 
	"ASSESSMENT_END_TIME" TIMESTAMP (6), 
	"ASSESSMENT_ASSIGNED_BY_FK" NUMBER, 
	"CANDIDATE_EMAIL_ID" VARCHAR2(100 BYTE), 
	"URL" VARCHAR2(2000 BYTE), 
	"URL_HASH_CODE" VARCHAR2(2000 BYTE), 
	"INTERVIEW_ROUND" VARCHAR2(10 BYTE), 
	 CONSTRAINT "OC_TBL_CANDIDATES_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "OC_TBL_CANDIDATES_FK1" FOREIGN KEY ("ASSESSMENT_ASSIGNED_BY_FK")
	  REFERENCES "SYSTEM"."OC_TBL_ADMIN" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

